// ─── Put Flow Viewer — Configuration ──────────────────────────────────────────
//
// Positions data comes from positions.json, generated by fetch_premiums.py.
// No Google API key needed here.
//
// CORS proxy is required for Yahoo Finance price data (browser restriction).
// Alternatives if the default is slow:
//   'https://api.allorigins.win/raw?url='
//   'https://api.codetabs.com/v1/proxy?quest='
//
// ──────────────────────────────────────────────────────────────────────────────

const CONFIG = {
  CORS_PROXY: 'https://corsproxy.io/?',
  AI_WORKER:  'https://options-ai.YOUR-SUBDOMAIN.workers.dev',
};
